### ISSUE TITLE
直接添加使用显示错误如下

### ISSUE THREAD

**Issue by jinyuyoulong** [shuiRong/hexo-theme-Ada#1]
doctype html html include partial/head.jade body #container #topnav br br span#subtitle #{config.subtitle} br br span#description #{config.description} br br include partial/nav.jade include partial/content.jade //- include partial/footer.jade script(src='/js/mouseover.js')

**Comment by shuiRong** [comment]
这是因为Ada用的是Jade模板，没有安装依赖导致的。（是我的锅，忘了在README里说明）
解决方法：在博客根目录下 : `npm install hexo-renderer-jade --save`
